services:
  service-backend:
    build:
      context: ./caccoId
      cache_from: []
    container_name: backend
    ports:
      - '8080:8080'
    networks:
      - caccoid
    env_file:
      - ./caccoId/.env
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:8080/actuator/health || exit 1']
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  service-frontend:
    container_name: frontend
    build:
      context: ./caccoid-front
    ports:
      - '5173:5173'
    volumes:
      - ./caccoid-front:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - caccoid
    depends_on:
      service-backend:
        condition: service_healthy
    environment:
      - CHOKIDAR_USEPOLLING=true
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Painel Admin
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - caccoid
volumes:
  minio_data:
networks:
  caccoid:
